//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minsky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minsky.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Admin commands:
        ///`?start` - start server
        ///`?restart` - restart server
        ///`?stop` - stop server.
        /// </summary>
        internal static string AdminHelp {
            get {
                return ResourceManager.GetString("AdminHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS &amp; SRS are running.
        /// </summary>
        internal static string AllRunning {
            get {
                return ResourceManager.GetString("AllRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t comply!.
        /// </summary>
        internal static string CantComplyMessage {
            get {
                return ResourceManager.GetString("CantComplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in commands to get info:
        ///`?server` - to get server info and srs address
        ///`?status` - to get current server status
        ///`?utc` - to get current UTC time.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is off, nothing to stop!.
        /// </summary>
        internal static string NothingToStopMessage {
            get {
                return ResourceManager.GetString("NothingToStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :red_circle:.
        /// </summary>
        internal static string OfflineEmoji {
            get {
                return ResourceManager.GetString("OfflineEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **OFFLINE**.
        /// </summary>
        internal static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :green_circle:.
        /// </summary>
        internal static string OnlineEmoji {
            get {
                return ResourceManager.GetString("OnlineEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **ONLINE**.
        /// </summary>
        internal static string OnlineMessage {
            get {
                return ResourceManager.GetString("OnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use `?restart`.
        /// </summary>
        internal static string PleaseUseRestart {
            get {
                return ResourceManager.GetString("PleaseUseRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS and SRS are restarted.
        /// </summary>
        internal static string RestartedMessage {
            get {
                return ResourceManager.GetString("RestartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting, please wait....
        /// </summary>
        internal static string RestartingMessage {
            get {
                return ResourceManager.GetString("RestartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} DCS server is {1}
        ///{2} SRS server is {3}.
        /// </summary>
        internal static string ServerStatusMessageTemplate {
            get {
                return ResourceManager.GetString("ServerStatusMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running.
        /// </summary>
        internal static string SingleRunningTemplate {
            get {
                return ResourceManager.GetString("SingleRunningTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong!.
        /// </summary>
        internal static string SomethingWentWrongMessage {
            get {
                return ResourceManager.GetString("SomethingWentWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS and SRS are started.
        /// </summary>
        internal static string StartedMessage {
            get {
                return ResourceManager.GetString("StartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting, please wait....
        /// </summary>
        internal static string StartingMessage {
            get {
                return ResourceManager.GetString("StartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS &amp; SRS are stopped.
        /// </summary>
        internal static string StoppedMessage {
            get {
                return ResourceManager.GetString("StoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping, please wait....
        /// </summary>
        internal static string StoppingMessage {
            get {
                return ResourceManager.GetString("StoppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command, try `?help`.
        /// </summary>
        internal static string UknownCommandMessage {
            get {
                return ResourceManager.GetString("UknownCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m in **DEBUG** mode, won&apos;t comply to you!.
        /// </summary>
        internal static string WontComplyMessage {
            get {
                return ResourceManager.GetString("WontComplyMessage", resourceCulture);
            }
        }
    }
}
